apiVersion: v1
kind: Pod
metadata:
  name: hawaian-pod-2
  labels:
    app: hawaian-pod
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: hawaian-pod-3
  labels:
    app: hawaian-pod
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80