apiVersion: v1
kind: Pod
metadata:
  name: web-3
  labels:
    app: web-app
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']