apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web-app
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']

---
apiVersion: v1
kind: Pod
metadata:
  name: web-2
  labels:
    app: web-app
spec:
  containers:
    - image: nginx
      name: nginx
      ports:
        - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: web-3
  labels:
    app: web-app
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']